yandereWaifu.LoveRoomPool = {
	{ item = CollectibleType.COLLECTIBLE_HEART, DecreaseBy=1, RemoveOn=0.1, Weight=1 },
	{ item = CollectibleType.COLLECTIBLE_YUM_HEART, DecreaseBy=1, RemoveOn=0.1, Weight=1 },
	{ item = CollectibleType.COLLECTIBLE_YUCK_HEART, DecreaseBy=1, RemoveOn=0.1, Weight=1 },
	{ item = CollectibleType.COLLECTIBLE_CANDY_HEART, DecreaseBy=1, RemoveOn=0.1, Weight=1 },
	{ item = CollectibleType.COLLECTIBLE_EMPTY_HEART, DecreaseBy=1, RemoveOn=0.1, Weight=1 },
	{ item = CollectibleType.COLLECTIBLE_HEARTBREAK, DecreaseBy=1, RemoveOn=0.1, Weight=1 },
	{ item = CollectibleType.COLLECTIBLE_BBF, DecreaseBy=1, RemoveOn=0.1, Weight=1 },
	{ item = CollectibleType.COLLECTIBLE_BFFS, DecreaseBy=1, RemoveOn=0.1, Weight=1 },
	{ item = CollectibleType.COLLECTIBLE_SKATOLE, DecreaseBy=1, RemoveOn=0.1, Weight=1 },
	{ item = CollectibleType.COLLECTIBLE_MULLIGAN, DecreaseBy=1, RemoveOn=0.1, Weight=1 },
	{ item = CollectibleType.COLLECTIBLE_DIRTY_MIND, DecreaseBy=1, RemoveOn=0.1, Weight=1 },
	{ item = CollectibleType.COLLECTIBLE_HYPERCOAGULATION, DecreaseBy=1, RemoveOn=0.1, Weight=1 },
	{ item = CollectibleType.COLLECTIBLE_SOUL_LOCKET, DecreaseBy=1, RemoveOn=0.1, Weight=1 },
	{ item = RebekahCurse.Items.COLLECTIBLE_TIGHTHAIRTIE, DecreaseBy=1, RemoveOn=0.1, Weight=1 },
	{ item = RebekahCurse.Items.COLLECTIBLE_HEARTSANDCRAFTS, DecreaseBy=1, RemoveOn=0.1, Weight=1 },
	{ item = RebekahCurse.Items.COLLECTIBLE_TECHHZ, DecreaseBy=1, RemoveOn=0.1, Weight=1 },
	{ item = RebekahCurse.Items.COLLECTIBLE_LOVESICK, DecreaseBy=1, RemoveOn=0.1, Weight=1 },
	{ item = RebekahCurse.Items.COLLECTIBLE_SNAP, DecreaseBy=1, RemoveOn=0.1, Weight=1 },
	{ item = RebekahCurse.Items.COLLECTIBLE_REBEKAHSFAVORITE, DecreaseBy=1, RemoveOn=0.1, Weight=1 },
}
