yandereWaifu.dss_rebekahbasics = {
	title = 'rebekah basics',
	fsize = 2,
	nocursor = true,
	scroller = true,
	buttons = {
		{str = 'rebekah is'},
		{str = 'many characters', clr = 3},
		{str = 'in one!'},
		{str = ''},
		{str = 'each version'},
		{str = 'of rebekah is called'},
		{str = 'personalities.', clr = 3},
		{str = ''},
		{str = 'each personality has a'},
		{str = 'dash move', clr = 3},
		{str = 'with a'},
		{str = 'powerful pocket item!', clr = 3},
		{str = ''},
		{str = 'double tap move', clr = 3},
		{str = 'to trigger a'},
		{str = 'dash or special', clr = 3},
		{str = 'move.', clr = 3},
		{str = ''},
		{str = 'using your pocket item'},
		{str = 'triggers a powerful attack'},
		{str = 'with a cost.', clr = 3},
		{str = ''},
		{str = 'double tap move', clr = 3},
		{str = 'input can be'},
		{str = 'changed', clr = 3},
		{str = 'at the settings.', clr = 3},
		{str = ''},
		{str = 'rebekah has a heart cap'},
		{str = 'as well, with a limit of'},
		{str = '3 red hearts and'},
		{str = '3 nonred hearts'},
	},
	--[[generate = function()
		lib.GetSaveData().ViewedTutorial = true
	end,]]
	tooltip = {strset = {'rebekah', 'the', 'nerd'}}
}

yandereWaifu.dss_rebekahadvanced = {
	title = 'rebekah advanced',
	fsize = 2,
	nocursor = true,
	scroller = true,
	buttons = {
		{str = 'rebekah has a special bar'},
		{str = 'called'},
		{str = 'her passion bar.', clr = 3},
		{str = ''},
		{str = 'any time rebekah'},
		{str = 'kills an enemy'},
		{str = 'a heart fragment'},
		{str = 'fills her passion bar'},
		{str = ''},
		{str = 'upon filling,'},
		{str = 'she gains a full'},
		{str = 'heart stock'},
		{str = ''},
		{str = 'a heart stock'},
		{str = 'can be used to'},
		{str = 'use your pocket'},
		{str = 'item'},
		{str = ''},
		{str = 'by default,'},
		{str = 'rebekah has 3 heart'},
		{str = 'stocks'},
		{str = ''},
		{str = 'to increase your'},
		{str = 'max heart stock,'},
		{str = 'exceed your heart container'},
		{str = 'limit'},
		{str = ''},
		{str = 'each extra heart container'},
		{str = 'gets converted to a new'},
		{str = 'stock'},
		{str = ''},
		{str = 'each personality has'},
		{str = 'a different amount', clr = 3},
		{str = 'of bar points'},
		{str = 'to fill the bar'},
		{str = 'eg. nerd has 50 points'},
		{str = 'while aloof has 100'},
	},
	tooltip = {strset = {'nerd more', 'for the', 'nerd'}}
}




--- TAINTED ---
yandereWaifu.dss_rebekahtbasics = {
	title = 'tainted rebekah basics',
	fsize = 2,
	nocursor = true,
	scroller = true,
	buttons = {
		{str = 'tainted rebekah is'},
		{str = 'sad', clr = 3},
		{str = ''},
		{str = 'so instead'},
		{str = 'of heart based'},
		{str = 'personalities,', clr = 3},
		{str = 'she takes'},
		{str = 'curses', clr = 3},
		{str = 'to cope'},
		{str = 'the loss of'},
		{str = 'her crush'},
		{str = ''},
		{str = 'rebekah now has'},
		{str = 'a healthbar', clr = 3},
		{str = 'for health'},
		{str = ''},
		{str = 'her healthbar allows her'},
		{str = 'to have more hitpoints'},
		{str = 'but her invincibility', clr = 3},
		{str = 'frames are shorter', clr = 3},
		{str = ''},
		{str = 'to increase max'},
		{str = 'healthbar, get'},
		{str = 'items that increase'},
		{str = 'your max red hearts'},
		{str = ''},
		{str = 'each personality has'},
		{str = 'four skills', clr = 3},
		{str = 'triggered by her'},
		{str = 'pocket item', clr = 3},
		{str = ''},
		{str = 'most of her skills'},
		{str = 'cost'},
		{str = 'rage crystals', clr = 3},
		{str = ''},
		{str = 'rage crystals'},
		{str = 'are points'},
		{str = 'gained by every'},
		{str = 'other basic attack', clr = 3},
		{str = ''},
		{str = 'by default,'},
		{str = 'rebekah can have'},
		{str = 'only two max crystals'},
		{str = 'but some skills'},
		{str = 'cost more than two'},
		{str = ''},
		{str = 'to increase your rage,'},
		{str = 'kill bosses to drop', clr = 3},
		{str = 'crystal fragments'},
		{str = ''},
		{str = 'gain up to 3'},
		{str = 'to increase your cap'},
		{str = 'by one'},
		{str = ''},
	},
	--[[generate = function()
		lib.GetSaveData().ViewedTutorial = true
	end,]]
	tooltip = {strset = {'rebekah', 'weeps'}}
}